"""
powerflow-report.py — populate PF_Master.xlsx with EasyPower simulation results.

Reads sc_XX_det.xlsx and sc_XX_sum.xlsx (generated by build_master.py from HTM
reports), extracts bus-level power-flow and transformer results per scenario,
and fills in the PF_Master.xlsx template.

Output: PF_Master_IFC.xlsx (a copy of PF_Master.xlsx with data populated).

Run standalone (interactive — asks where the report files are):
    python powerflow-report.py
or quick:
    python powerflow-report.py <input_folder> [output_folder]
It also runs automatically at the end of easypower_batch_reports.py.

Needs: pip install pandas openpyxl
"""

import os
import re
import sys
from pathlib import Path

import numpy as np

# NumPy 2.x removed deprecated aliases like np.float, np.int, np.bool.
# Some libraries (e.g. openpyxl with older pandas) still reference them.
for _name, _val in (("float", float), ("int", int), ("bool", bool),
                     ("complex", complex)):
    if not hasattr(np, _name):
        setattr(np, _name, _val)

import pandas as pd

# --------------------------------------------------------------------------- CONFIG
DECIMALS_POWER = 3      # kW / kVAR
DECIMALS_VOLTAGE = 4    # Vpu boundaries
DECIMALS_TAP = 6        # MPT Tap %
DECIMALS_CURRENT = 1    # Amperes
DECIMALS_PF = 6         # Power factor

# Bus names used for per-scenario lookups
POI_BUS = "POI"
PV_BUS = "INV_PV1"
BESS_BUS = "INV_MB6"
DASH = "-"

# Column names for the det file (read with skiprows=4, header=None)
DET_COLUMNS = [
    "Bus Name", "Vpu", "Deg", "Generation kW", "Generation kVAR",
    "Load kW", "Load kVAR", "CAP/REAC kVAR",
    "Line Flows To Bus Name", "Line Flows Branch Name",
    "Line Flows kW", "Line Flows kVAR", "Line Flows Amps"
]

# Transformer names for MPT1/MPT2 in the SUM Transformer Overload report
MPT1_NAME = "VJR4"
MPT2_NAME = "VJR5"
MPT1_BUS = "BUS-5"     # Secondary bus for VJR4
MPT2_BUS = "BUS-6"     # Secondary bus for VJR5

# Equipment ratings (used to fill design-limit columns)
MAX_ISU_PV_CURRENT = 3938.5
MAX_ISU_BESS_CURRENT = 7649.9
MAX_MPT_CURRENT = 2510.2


# --------------------------------------------------------------------------- helpers
def _key(p):
    """Sort by scenario number.  Files that don't match sort at the end."""
    m = re.match(r"sc_(\d+)", p.stem)
    if m:
        return (int(m.group(1)), p.stem)
    return (float("inf"), p.stem)


def _pf_from_pq(kw, kvar):
    """Power factor from active/reactive power.  Returns 0 if both are 0."""
    if kw == 0 and kvar == 0:
        return 0.0
    kw, kvar = abs(float(kw)), abs(float(kvar))
    return round(kw / (kw ** 2 + kvar ** 2) ** 0.5, DECIMALS_PF)


def _safe_val(row_df, col, decimals):
    """Extract *col* from the first row of *row_df*, rounded to *decimals*."""
    if row_df.empty or col not in row_df.columns:
        return 0
    val = row_df[col].values[0]
    return round(float(val), decimals) if pd.notna(val) else 0


def _safe_line_flow(poi_df, col, decimals):
    """Extract *col* from the first line-flow row of *poi_df*.

    The POI bus row has generation columns (all zero) followed by
    line-flow sub-rows.  We read the first sub-row's value from *col*.
    """
    if poi_df.empty or col not in poi_df.columns:
        return 0, False
    # The first row has the bus Gen data, subsequent rows are line flows.
    # If there are at least 2 rows, row 1 is the first line flow.
    if len(poi_df) < 2:
        return 0, False
    val = poi_df[col].values[1]
    is_neg = pd.notna(val) and float(val) < 0
    return (round(float(val), decimals) if pd.notna(val) else 0), is_neg


def _is_idle(row_df):
    """Return True if the bus has effectively zero real power generation."""
    if row_df.empty:
        return True
    kw = _safe_val(row_df, "Generation kW", 0)
    return abs(kw) < 0.5


def _pf_or_dash(kw, kvar):
    """Return PF string, or '-' if real power is near zero (idle unit)."""
    kw, kvar = abs(float(kw)), abs(float(kvar))
    if kw < 0.5:
        return DASH
    return round(kw / (kw ** 2 + kvar ** 2) ** 0.5, DECIMALS_PF)


# ------------------------------------------------------------------------- SUM file readers
def _parse_sum_mpt_currents(sum_df):
    """Extract MPT1/MPT2 load amps from the Transformer Overload section.

    Supports both old format (section intro "Transformer Overload Report") and
    new format (direct column header starting with "Transformer Name").
    """
    mpt1_curr = 0.0
    mpt2_curr = 0.0
    in_overload = False
    header_found = False

    for idx in range(len(sum_df)):
        row_str = " | ".join(str(v) for v in sum_df.iloc[idx].values if pd.notna(v))

        # OLD format: section header text
        if "Transformer Overload Report" in row_str:
            in_overload = True
            header_found = False
            continue

        # NEW format: direct column header row
        if ("Transformer Name" in row_str and "Transformer Rated Amps" in row_str
                and "Load Load Amps" in row_str):
            in_overload = True
            header_found = True
            continue

        if not in_overload:
            continue

        # OLD format: column sub-header
        if not header_found and ("Name | From Bus Name" in row_str or "Transformer | Load" in row_str):
            header_found = True
            continue

        if not header_found:
            continue

        if "Overload Threshold" in row_str:
            continue

        if MPT1_NAME in row_str and MPT1_BUS in row_str and "Secondary" in row_str:
            parts = [str(v) for v in sum_df.iloc[idx].values if pd.notna(v)]
            if len(parts) >= 5:
                try:
                    mpt1_curr = float(parts[4])
                except ValueError:
                    pass

        if MPT2_NAME in row_str and MPT2_BUS in row_str and "Secondary" in row_str:
            parts = [str(v) for v in sum_df.iloc[idx].values if pd.notna(v)]
            if len(parts) >= 5:
                try:
                    mpt2_curr = float(parts[4])
                except ValueError:
                    pass

        if "Line Overload Report" in row_str or "Line From Bus Name" in row_str:
            break

    return mpt1_curr, mpt2_curr


def _parse_sum_mpt_taps(sum_df):
    """Extract MPT1/MPT2 tap positions from the Transformer Tap section.

    Supports both old format (section intro "Transformer Tap Report") and
    new format (direct column header starting with "Transformer Name").

    Returns (mpt1_tap_pct, mpt2_tap_pct).  The tap % is calculated from
    (tap_kV - base_kV) / base_kV * 100.
    """
    mpt1_tap = 0.0
    mpt2_tap = 0.0
    in_tap = False
    header_found = False

    for idx in range(len(sum_df)):
        row_str = " | ".join(str(v) for v in sum_df.iloc[idx].values if pd.notna(v))

        # OLD format: section header text
        if "Transformer Tap Report" in row_str:
            in_tap = True
            header_found = False
            continue

        # NEW format: direct column header row
        if ("Transformer Name" in row_str and "Connection From Bus Name" in row_str
                and "Base kV From" in row_str):
            in_tap = True
            header_found = True
            continue

        if not in_tap:
            continue

        # OLD format: column sub-header
        if not header_found and ("Name | From Bus Name" in row_str or "Transformer | Connection" in row_str):
            header_found = True
            continue

        if not header_found:
            continue

        # Stop at next major section (old format)
        if "Overload Report" in row_str or "Generation Summary" in row_str:
            break
        # Stop at next major section (new format)
        if "Line From Bus Name" in row_str:
            break

        parts = [str(v) for v in sum_df.iloc[idx].values if pd.notna(v)]

        # VJR4 BUS-5 Secondary tap
        if MPT1_NAME in row_str and MPT1_BUS in row_str:
            if len(parts) >= 5:
                try:
                    base_kv = float(parts[3])
                    tap_kv = float(parts[4])
                    if base_kv > 0:
                        mpt1_tap = round((tap_kv - base_kv) / base_kv * 100, DECIMALS_TAP)
                except (ValueError, IndexError):
                    pass

        # VJR5 BUS-6 Secondary tap
        if MPT2_NAME in row_str and MPT2_BUS in row_str:
            if len(parts) >= 5:
                try:
                    base_kv = float(parts[3])
                    tap_kv = float(parts[4])
                    if base_kv > 0:
                        mpt2_tap = round((tap_kv - base_kv) / base_kv * 100, DECIMALS_TAP)
                except (ValueError, IndexError):
                    pass

    return mpt1_tap, mpt2_tap


# --------------------------------------------------------------------------- sheet population
def _populate_power(df_p, sc, poi_flow_kw, poi_flow_kvar, pv_row, bess_row):
    """Fill the 'Scenario 100%_Power' row for one scenario."""
    mask = df_p["Scenario"] == sc
    if not mask.any():
        return

    # POI power from line flow (POI bus has no generation data)
    df_p.loc[mask, "Simulation results - Real power at POI (kW)"] = (
        round(poi_flow_kw, DECIMALS_POWER)
    )
    df_p.loc[mask, "Simulation results - Reactive power at POI (kVAR)"] = (
        round(poi_flow_kvar, DECIMALS_POWER)
    )

    # PV skid
    pv_kw = _safe_val(pv_row, "Generation kW", DECIMALS_POWER)
    pv_kvar = _safe_val(pv_row, "Generation kVAR", DECIMALS_POWER)
    df_p.loc[mask, "Gross Active Power Supplied Per PV Skid (kW)"] = pv_kw
    df_p.loc[mask, "Gross Reactive Power Supplied Per PV Skid (kVAR)"] = pv_kvar

    # BESS skid — negate reactive power to match report sign convention
    # INV_MB6 is one half of the BESS plant; multiply by 2 for total skid power
    bess_kw = _safe_val(bess_row, "Generation kW", DECIMALS_POWER) * 2
    bess_kvar = -_safe_val(bess_row, "Generation kVAR", DECIMALS_POWER) * 2
    df_p.loc[mask, "Gross Active Power Supplied Per BESS Skid (kW)"] = bess_kw
    df_p.loc[mask, "Gross Reactive Power Supplied Per BESS Skid (kVAR)"] = bess_kvar

    # Cast PF columns to object to allow string values like '-'
    for col in ["Simulation results - Power Factor at POI", "PV INV PF", "BESS INV PF"]:
        if col in df_p.columns:
            df_p[col] = df_p[col].astype(object)

    # Power factors — use '-' when the unit type is idle
    df_p.loc[mask, "Simulation results - Power Factor at POI"] = (
        _pf_or_dash(poi_flow_kw, poi_flow_kvar)
    )
    df_p.loc[mask, "PV INV PF"] = _pf_or_dash(pv_kw, pv_kvar)
    df_p.loc[mask, "BESS INV PF"] = _pf_or_dash(bess_kw, bess_kvar)


def _populate_voltages(df_v, sc, vpu_inv, vpu_coll, mpt_tap):
    """Fill the 'Scenario_100_inv_voltages' row for one scenario."""
    mask = df_v["Scenario"] == sc
    if not mask.any():
        return

    df_v.loc[mask, "Highest Inverter LV Voltage (%)"] = (
        round(float(vpu_inv.max()), DECIMALS_VOLTAGE) if not vpu_inv.empty else 0
    )
    df_v.loc[mask, "Lowest Inverter LV Voltage (%)"] = (
        round(float(vpu_inv.min()), DECIMALS_VOLTAGE) if not vpu_inv.empty else 0
    )
    df_v.loc[mask, "Highest Collector System MV Voltage (%)"] = (
        round(float(vpu_coll.max()), DECIMALS_VOLTAGE) if not vpu_coll.empty else 0
    )
    df_v.loc[mask, "Lowest Collector System MV Voltage (%)"] = (
        round(float(vpu_coll.min()), DECIMALS_VOLTAGE) if not vpu_coll.empty else 0
    )
    df_v.loc[mask, "MPT1 HS OLTC Tap(%)"] = mpt_tap


def _populate_branch_loading(df_l, sc, mpt1_curr, mpt2_curr, pv_amps, bess_amps):
    """Fill the 'Scenario_100_Branch_loading' row for one scenario."""
    mask = df_l["Scenario"] == sc
    if not mask.any():
        return

    mpt1 = round(float(mpt1_curr), DECIMALS_CURRENT) if pd.notna(mpt1_curr) else 0
    mpt2 = round(float(mpt2_curr), DECIMALS_CURRENT) if pd.notna(mpt2_curr) else 0
    max_mpt = MAX_MPT_CURRENT
    max_pv = round(float(pv_amps.max()), DECIMALS_CURRENT) if not pv_amps.empty else 0
    max_bess = round(float(bess_amps.max()), DECIMALS_CURRENT) if not bess_amps.empty else 0

    df_l.loc[mask, "Current through MPT1 (A)"] = mpt1
    df_l.loc[mask, "Current through MPT2 (A)"] = mpt2
    df_l.loc[mask, "Max allowed current through MPT (A)"] = max_mpt
    df_l.loc[mask, "Max ISU PV current (A)"] = max_pv
    df_l.loc[mask, "Max ISU BESS current (A)"] = max_bess
    df_l.loc[mask, "Max allowed current through ISU PV (A)"] = MAX_ISU_PV_CURRENT
    df_l.loc[mask, "Max allowed current through ISU BESS (A)"] = MAX_ISU_BESS_CURRENT
    df_l.loc[mask, "MPT1 % loading"] = round(mpt1 / max_mpt * 100, 2) if max_mpt else 0
    df_l.loc[mask, "MPT2 % loading"] = round(mpt2 / max_mpt * 100, 2) if max_mpt else 0


# --------------------------------------------------------------------------- build
def build(input_folder, output_folder=None):
    """Read per-scenario det/sum files from *input_folder* and fill PF_Master.xlsx.

    PF_Master.xlsx is expected alongside this script.  The populated workbook
    is written to *output_folder* (defaults to ``input_folder/ez_automation_output``).
    """
    in_dir = Path(input_folder)
    out_dir = Path(output_folder) if output_folder else in_dir / "ez_automation_output"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Locate the master template — try script directory, then input directory
    master_path = Path(__file__).parent / "PF_Master.xlsx"
    if not master_path.exists():
        master_path = in_dir / "PF_Master.xlsx"
    if not master_path.exists():
        print(f"Error: PF_Master.xlsx not found (looked in {Path(__file__).parent} and {in_dir}).")
        return

    print(f"Loading Master File ({master_path})...")
    xls = pd.ExcelFile(master_path)
    sheets = {name: xls.parse(name) for name in xls.sheet_names}

    # ---- discover scenario files -------------------------------------------
    det_files = sorted(in_dir.glob("sc_*_det.xlsx"), key=_key)
    sum_files = sorted(in_dir.glob("sc_*_sum.xlsx"), key=_key)
    print(f"Found {len(det_files)} scenario files matching 'sc_XX_det.xlsx'.  Processing...")

    for det_path in det_files:
        m = re.match(r"sc_(\d+)", det_path.stem)
        if not m:
            continue
        sc = int(m.group(1))

        try:
            df_det = pd.read_excel(det_path, skiprows=4, header=None, names=DET_COLUMNS)

            # Normalise bus names
            df_det["Bus Name"] = df_det["Bus Name"].astype(str).str.strip()
            df_det["Line Flows To Bus Name"] = (
                df_det["Line Flows To Bus Name"].astype(str).str.strip()
            )

            # ---- 1. Scenario 100%_Power -----------------------------------
            # POI power — read FROM the POI bus line flow (POI has no generation)
            # The first sub-row after the POI bus name is the line flow.
            poi_df = df_det[df_det["Bus Name"] == POI_BUS]
            poi_flow_kw = 0.0
            poi_flow_kvar = 0.0
            if not poi_df.empty:
                v1 = poi_df["Line Flows kW"].values[0]
                v2 = poi_df["Line Flows kVAR"].values[0]
                poi_flow_kw = float(v1) if pd.notna(v1) else 0.0
                poi_flow_kvar = float(v2) if pd.notna(v2) else 0.0

            pv_row = df_det[df_det["Bus Name"] == PV_BUS]
            bess_row = df_det[df_det["Bus Name"] == BESS_BUS]

            if "Scenario 100%_Power" in sheets:
                _populate_power(sheets["Scenario 100%_Power"], sc,
                                poi_flow_kw, poi_flow_kvar, pv_row, bess_row)

            # ---- 2. Scenario_100_inv_voltages -----------------------------
            inv_mask = df_det["Bus Name"].str.startswith("INV_", na=False)
            vpu_inv = pd.to_numeric(df_det.loc[inv_mask, "Vpu"], errors="coerce").dropna()

            # Collector system MV buses — switchgear at 34.5 kV
            coll_mask = df_det["Bus Name"].str.match(r"^SWGR_", na=False)
            vpu_coll = pd.to_numeric(df_det.loc[coll_mask, "Vpu"], errors="coerce").dropna()

            # MPT tap from SUM file
            mpt_tap = 0.0
            sum_path = in_dir / f"sc_{sc:02d}_sum.xlsx"
            if sum_path.exists():
                try:
                    df_sum = pd.read_excel(sum_path, header=None)
                    mpt1_tap, mpt2_tap = _parse_sum_mpt_taps(df_sum)
                    # Use MPT1 (VJR4) tap as the primary
                    mpt_tap = mpt1_tap
                except Exception:
                    pass

            if "Scenario_100_inv_voltages" in sheets:
                _populate_voltages(sheets["Scenario_100_inv_voltages"], sc,
                                   vpu_inv, vpu_coll, mpt_tap)

            # ---- 3. Scenario_100_Branch_loading ---------------------------
            # MPT currents from SUM Transformer Overload section
            mpt1_curr = 0.0
            mpt2_curr = 0.0
            if sum_path.exists():
                try:
                    df_sum = pd.read_excel(sum_path, header=None)
                    mpt1_curr, mpt2_curr = _parse_sum_mpt_currents(df_sum)
                except Exception:
                    pass

            # ISU currents from DET line flows
            pv_flow_mask = df_det["Bus Name"].str.contains("INV_PV", na=False, regex=False)
            pv_amps = pd.to_numeric(
                df_det.loc[pv_flow_mask, "Line Flows Amps"], errors="coerce"
            ).dropna()

            bess_flow_mask = df_det["Bus Name"].str.contains("INV_MB", na=False, regex=False)
            bess_amps = pd.to_numeric(
                df_det.loc[bess_flow_mask, "Line Flows Amps"], errors="coerce"
            ).dropna()

            # Zero out ISU current when the unit is idle
            if _is_idle(pv_row):
                pv_amps = pd.Series(dtype=float)
            if _is_idle(bess_row):
                bess_amps = pd.Series(dtype=float)

            if "Scenario_100_Branch_loading" in sheets:
                _populate_branch_loading(sheets["Scenario_100_Branch_loading"], sc,
                                         mpt1_curr, mpt2_curr, pv_amps, bess_amps)

            print(f"  Scenario {sc} processed.")

        except Exception as e:
            print(f"  Error processing {det_path.name}: {e}")

    # ---- write output ------------------------------------------------------
    output_path = out_dir / "PF_Master_IFC.xlsx"
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        for name, df in sheets.items():
            df.to_excel(writer, sheet_name=name, index=False)

    print(f"\nDone.  Saved to {output_path}")


def banner():
    """Styled title block (matches easypower_batch_reports.py / build_master.py)."""
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    lines = [
        "EasyPower Reporting Automation",
        "Copyright \u00a9 Power-Link Technologies 2026",
        "",
        "Reach out to cooper@powerlinktec.com",
        "for troubleshooting and for reporting bugs",
    ]
    w = max(len(s) for s in lines) + 6
    print("\n" + "\u2554" + "\u2550" * w + "\u2557")
    for s in lines:
        print("\u2551" + s.center(w) + "\u2551")
    print("\u255a" + "\u2550" * w + "\u255d\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        build(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
    else:
        banner()
        while True:
            src = input("Folder containing the sc_XX_det.xlsx files (ez_automation_output folder): ").strip().strip('"')
            if Path(src).is_dir():
                break
            print("   That folder doesn't exist — try again.")
        dst = input(f"Output folder (for PF_Master_IFC.xlsx) [{src}]: ").strip().strip('"')
        build(src, dst or src)
