"""
powerflow-report.py — populate PF_Master.xlsx with EasyPower simulation results.

Reads sc_XX_det.xlsx (generated by build_master.py from HTM reports), extracts
bus-level power-flow results per scenario, and fills in the PF_Master.xlsx
template.

Output: PF_Master_IFC.xlsx (a copy of PF_Master.xlsx with data populated).

Run standalone (interactive — asks where the report files are):
    python powerflow-report.py
or quick:
    python powerflow-report.py <input_folder> [output_folder]
It also runs automatically at the end of easypower_batch_reports.py.

Needs: pip install pandas openpyxl
"""

import os
import re
import sys
from pathlib import Path

import numpy as np

# NumPy 2.x removed deprecated aliases like np.float, np.int, np.bool.
# Some libraries (e.g. openpyxl with older pandas) still reference them.
for _name, _val in (("float", float), ("int", int), ("bool", bool),
                     ("complex", complex)):
    if not hasattr(np, _name):
        setattr(np, _name, _val)

import pandas as pd

# --------------------------------------------------------------------------- CONFIG
DECIMALS_POWER = 3      # kW / kVAR
DECIMALS_VOLTAGE = 3    # Vpu boundaries
DECIMALS_TAP = 6        # MPT Tap %
DECIMALS_CURRENT = 1    # Amperes
DECIMALS_PF = 6         # Power factor

# Bus names used for per-scenario lookups
POI_BUS = "BUS-11"
PV_BUS = "INV_PV1"
BESS_BUS = "INV_MB6"

# Column names for the det file (read with skiprows=4, header=None)
DET_COLUMNS = [
    "Bus Name", "Vpu", "Deg", "Generation kW", "Generation kVAR",
    "Load kW", "Load kVAR", "CAP/REAC kVAR",
    "Line Flows To Bus Name", "Line Flows Branch Name",
    "Line Flows kW", "Line Flows kVAR", "Line Flows Amps"
]

# Equipment ratings (used to fill design-limit columns)
MAX_ISU_PV_CURRENT = 3938.5
MAX_ISU_BESS_CURRENT = 7649.9
MAX_MPT_CURRENT = 2510.2


# --------------------------------------------------------------------------- helpers
def _key(p):
    """Sort by scenario number.  Files that don't match sort at the end."""
    m = re.match(r"sc_(\d+)", p.stem)
    if m:
        return (int(m.group(1)), p.stem)
    return (float("inf"), p.stem)


def _pf_from_pq(kw, kvar):
    """Power factor from active/reactive power.  Returns 0 if both are 0."""
    kw, kvar = abs(float(kw)), abs(float(kvar))
    if kw == 0 and kvar == 0:
        return 0.0
    return round(kw / (kw ** 2 + kvar ** 2) ** 0.5, DECIMALS_PF)


def _safe_val(row_df, col, decimals):
    """Extract *col* from the first row of *row_df*, rounded to *decimals*."""
    if row_df.empty or col not in row_df.columns:
        return 0
    val = row_df[col].values[0]
    return round(float(val), decimals) if pd.notna(val) else 0


# --------------------------------------------------------------------------- sheet population
def _populate_power(df_p, sc, poi_row, pv_row, bess_row):
    """Fill the 'Scenario 100%_Power' row for one scenario."""
    mask = df_p["Scenario"] == sc
    if not mask.any():
        return

    df_p.loc[mask, "Simulation results - Real power at POI (kW)"] = (
        _safe_val(poi_row, "Generation kW", DECIMALS_POWER)
    )
    df_p.loc[mask, "Simulation results - Reactive power at POI (kVAR)"] = (
        _safe_val(poi_row, "Generation kVAR", DECIMALS_POWER)
    )
    df_p.loc[mask, "Gross Active Power Supplied Per PV Skid (kW)"] = (
        _safe_val(pv_row, "Generation kW", DECIMALS_POWER)
    )
    df_p.loc[mask, "Gross Reactive Power Supplied Per PV Skid (kVAR)"] = (
        _safe_val(pv_row, "Generation kVAR", DECIMALS_POWER)
    )
    df_p.loc[mask, "Gross Active Power Supplied Per BESS Skid (kW)"] = (
        _safe_val(bess_row, "Generation kW", DECIMALS_POWER)
    )
    df_p.loc[mask, "Gross Reactive Power Supplied Per BESS Skid (kVAR)"] = (
        _safe_val(bess_row, "Generation kVAR", DECIMALS_POWER)
    )

    poi_kw = abs(_safe_val(poi_row, "Generation kW", DECIMALS_POWER))
    poi_kvar = abs(_safe_val(poi_row, "Generation kVAR", DECIMALS_POWER))
    df_p.loc[mask, "Simulation results - Power Factor at POI"] = _pf_from_pq(poi_kw, poi_kvar)

    pv_kw = abs(_safe_val(pv_row, "Generation kW", DECIMALS_POWER))
    pv_kvar = abs(_safe_val(pv_row, "Generation kVAR", DECIMALS_POWER))
    df_p.loc[mask, "PV INV PF"] = _pf_from_pq(pv_kw, pv_kvar)

    bess_kw = abs(_safe_val(bess_row, "Generation kW", DECIMALS_POWER))
    bess_kvar = abs(_safe_val(bess_row, "Generation kVAR", DECIMALS_POWER))
    df_p.loc[mask, "BESS INV PF"] = _pf_from_pq(bess_kw, bess_kvar)


def _populate_voltages(df_v, sc, vpu_inv, vpu_coll, mpt_tap):
    """Fill the 'Scenario_100_inv_voltages' row for one scenario."""
    mask = df_v["Scenario"] == sc
    if not mask.any():
        return

    df_v.loc[mask, "Highest Inverter LV Voltage (%)"] = (
        round(float(vpu_inv.max()), DECIMALS_VOLTAGE) if not vpu_inv.empty else 0
    )
    df_v.loc[mask, "Lowest Inverter LV Voltage (%)"] = (
        round(float(vpu_inv.min()), DECIMALS_VOLTAGE) if not vpu_inv.empty else 0
    )
    df_v.loc[mask, "Highest Collector System MV Voltage (%)"] = (
        round(float(vpu_coll.max()), DECIMALS_VOLTAGE) if not vpu_coll.empty else 0
    )
    df_v.loc[mask, "Lowest Collector System MV Voltage (%)"] = (
        round(float(vpu_coll.min()), DECIMALS_VOLTAGE) if not vpu_coll.empty else 0
    )
    df_v.loc[mask, "MPT1 HS OLTC Tap(%)"] = mpt_tap


def _populate_branch_loading(df_l, sc, mpt1_curr, mpt2_curr, pv_amps, bess_amps):
    """Fill the 'Scenario_100_Branch_loading' row for one scenario."""
    mask = df_l["Scenario"] == sc
    if not mask.any():
        return

    mpt1 = round(float(mpt1_curr), DECIMALS_CURRENT) if pd.notna(mpt1_curr) else 0
    mpt2 = round(float(mpt2_curr), DECIMALS_CURRENT) if pd.notna(mpt2_curr) else 0
    max_mpt = MAX_MPT_CURRENT
    max_pv = round(float(pv_amps.max()), DECIMALS_CURRENT) if not pv_amps.empty else 0
    max_bess = round(float(bess_amps.max()), DECIMALS_CURRENT) if not bess_amps.empty else 0

    df_l.loc[mask, "Current through MPT1 (A)"] = mpt1
    df_l.loc[mask, "Current through MPT2 (A)"] = mpt2
    df_l.loc[mask, "Max allowed current through MPT (A)"] = max_mpt
    df_l.loc[mask, "Max ISU PV current (A)"] = max_pv
    df_l.loc[mask, "Max ISU BESS current (A)"] = max_bess
    df_l.loc[mask, "Max allowed current through ISU PV (A)"] = MAX_ISU_PV_CURRENT
    df_l.loc[mask, "Max allowed current through ISU BESS (A)"] = MAX_ISU_BESS_CURRENT
    df_l.loc[mask, "MPT1 % loading"] = round(mpt1 / max_mpt * 100, 2) if max_mpt else 0
    df_l.loc[mask, "MPT2 % loading"] = round(mpt2 / max_mpt * 100, 2) if max_mpt else 0


# --------------------------------------------------------------------------- build
def build(input_folder, output_folder=None):
    """Read per-scenario det files from *input_folder* and fill PF_Master.xlsx.

    PF_Master.xlsx is expected alongside this script.  The populated workbook
    is written to *output_folder* (defaults to ``input_folder/ez_automation_output``).
    """
    in_dir = Path(input_folder)
    out_dir = Path(output_folder) if output_folder else in_dir / "ez_automation_output"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Locate the master template — try script directory, then input directory
    master_path = Path(__file__).parent / "PF_Master.xlsx"
    if not master_path.exists():
        master_path = in_dir / "PF_Master.xlsx"
    if not master_path.exists():
        print(f"Error: PF_Master.xlsx not found (looked in {Path(__file__).parent} and {in_dir}).")
        return

    print(f"Loading Master File ({master_path})...")
    xls = pd.ExcelFile(master_path)
    sheets = {name: xls.parse(name) for name in xls.sheet_names}

    # ---- discover scenario files -------------------------------------------
    det_files = sorted(in_dir.glob("sc_*_det.xlsx"), key=_key)
    print(f"Found {len(det_files)} scenario files matching 'sc_XX_det.xlsx'.  Processing...")

    for det_path in det_files:
        m = re.match(r"sc_(\d+)", det_path.stem)
        if not m:
            continue
        sc = int(m.group(1))

        try:
            df_det = pd.read_excel(det_path, skiprows=4, header=None, names=DET_COLUMNS)

            # Normalise bus names
            df_det["Bus Name"] = df_det["Bus Name"].astype(str).str.strip()

            # ---- bus lookups (Scenario 100%_Power) -------------------------
            poi_row = df_det[df_det["Bus Name"] == POI_BUS]
            pv_row = df_det[df_det["Bus Name"] == PV_BUS]
            bess_row = df_det[df_det["Bus Name"] == BESS_BUS]

            if "Scenario 100%_Power" in sheets:
                _populate_power(sheets["Scenario 100%_Power"], sc, poi_row, pv_row, bess_row)

            # ---- voltage ranges (Scenario_100_inv_voltages) ----------------
            inv_mask = df_det["Bus Name"].str.startswith("INV_", na=False)
            vpu_inv = pd.to_numeric(df_det.loc[inv_mask, "Vpu"], errors="coerce").dropna()

            coll_mask = df_det["Bus Name"].str.match(r"^(SWGR_|BUS-\d)", na=False)
            vpu_coll = pd.to_numeric(df_det.loc[coll_mask, "Vpu"], errors="coerce").dropna()

            mpt_tap = 0.0

            if "Scenario_100_inv_voltages" in sheets:
                _populate_voltages(sheets["Scenario_100_inv_voltages"], sc, vpu_inv, vpu_coll, mpt_tap)

            # ---- branch loading (Scenario_100_Branch_loading) --------------
            mpt1_mask = (df_det["Bus Name"] == "BUS-11") & (df_det["Line Flows To Bus Name"] == "POI")
            mpt2_mask = (df_det["Bus Name"] == "V62-1") & (df_det["Line Flows To Bus Name"] == "POI")
            mpt1_curr = (
                pd.to_numeric(df_det.loc[mpt1_mask, "Line Flows Amps"], errors="coerce").max()
                if mpt1_mask.any() else 0
            )
            mpt2_curr = (
                pd.to_numeric(df_det.loc[mpt2_mask, "Line Flows Amps"], errors="coerce").max()
                if mpt2_mask.any() else 0
            )

            pv_flow_mask = df_det["Bus Name"].str.contains("INV_PV", na=False, regex=False)
            pv_amps = pd.to_numeric(df_det.loc[pv_flow_mask, "Line Flows Amps"], errors="coerce").dropna()

            bess_flow_mask = df_det["Bus Name"].str.contains("INV_MB", na=False, regex=False)
            bess_amps = pd.to_numeric(df_det.loc[bess_flow_mask, "Line Flows Amps"], errors="coerce").dropna()

            if "Scenario_100_Branch_loading" in sheets:
                _populate_branch_loading(sheets["Scenario_100_Branch_loading"], sc,
                                         mpt1_curr, mpt2_curr, pv_amps, bess_amps)

            print(f"  Scenario {sc} processed.")

        except Exception as e:
            print(f"  Error processing {det_path.name}: {e}")

    # ---- write output ------------------------------------------------------
    output_path = out_dir / "PF_Master_IFC.xlsx"
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        for name, df in sheets.items():
            df.to_excel(writer, sheet_name=name, index=False)

    print(f"\nDone.  Saved to {output_path}")


def banner():
    """Styled title block (matches easypower_batch_reports.py / build_master.py)."""
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    lines = [
        "EasyPower Reporting Automation",
        "Copyright \u00a9 Power-Link Technologies 2026",
        "",
        "Reach out to cooper@powerlinktec.com",
        "for troubleshooting and for reporting bugs",
    ]
    w = max(len(s) for s in lines) + 6
    print("\n" + "\u2554" + "\u2550" * w + "\u2557")
    for s in lines:
        print("\u2551" + s.center(w) + "\u2551")
    print("\u255a" + "\u2550" * w + "\u255d\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:                              # quick: folder on the command line
        build(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
    else:
        banner()
        while True:
            src = input("Folder containing the sc_XX_det.xlsx files (ez_automation_output folder): ").strip().strip('"')
            if Path(src).is_dir():
                break
            print("   That folder doesn't exist — try again.")
        dst = input(f"Output folder (for PF_Master_IFC.xlsx) [{src}]: ").strip().strip('"')
        build(src, dst or src)
